tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask-fonts"

cask "font-fira-code-nerd-font"
cask "docker"

tap "cantino/mcfly"
tap "cjbassi/ytop"
tap "derailed/k9s"
tap "heroku/brew"
tap "snyk/tap"


brew "cantino/mcfly/mcfly"
brew "cjbassi/ytop/ytop"
brew "derailed/k9s/k9s"
brew "farmotive/k8s/kpoof"
brew "heroku/brew/heroku"
brew "snyk/tap/snyk"


brew "angle-grinder"
brew "asdf"
brew "azure-cli"
brew "bat"
brew "coreutils"
brew "direnv"
brew "dive"
brew "dog"
brew "dust"
brew "fd"
brew "ffmpeg"
brew "git"
brew "git-extras"
brew "gitlab-runner"
brew "gitui"
brew "glib"
brew "gnupg"
brew "graphviz"
brew "hyperfine"
brew "imagemagick"
brew "jq"
brew "kubectx"
brew "legit"
brew "lsd"
brew "make"
brew "neovim"
brew "postgresql@13"
brew "procs"
brew "redis"
brew "rename"
brew "ripgrep"
brew "sd"
brew "snappy"
brew "starship"
brew "stern"
brew "tldr"
brew "tmux"
brew "tokei"
brew "tree"
brew "wget"
brew "xsv"
brew "youtubedr"
brew "zellig"
