tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask-fonts"
tap "microsoft/git"

# cask "claude-code" # The brew version of claude code does not get updates quickly, use their official install path
cask "1password-cli"
cask "container"
cask "docker"
cask "font-fira-code-nerd-font"
cask "ghostty"
cask "git-credential-manager-core"
cask "ksdiff"

tap "anomalyco/tap"
tap "cjbassi/ytop"
tap "derailed/k9s"

brew "cjbassi/ytop/ytop"
brew "derailed/k9s/k9s"

# brew "air" This is NOT the golang filewatcher, but something related to R
brew "angle-grinder"
brew "ansible"
brew "atuin"
brew "bat"
brew "codex"
brew "colima"
brew "coreutils"
brew "direnv"
brew "dive"
brew "dog"
brew "dust"
brew "fd"
brew "ffmpeg"
brew "gemini-cli"
brew "gh"
brew "git"
brew "git-extras"
brew "glib"
brew "gnupg"
brew "graphviz"
brew "hcloud"
brew "hyperfine"
brew "jq"
brew "krew"
brew "kustomize"
brew "lazygit"
brew "lsd"
brew "luarocks"
brew "make"
brew "mise" # asdf replacement
brew "neovim"
brew "opencode"
brew "procs"
brew "rename"
brew "ripgrep"
brew "sd"
brew "shellcheck"
brew "sqlite3"
brew "starship"
brew "tmux"
brew "tokei"
brew "tree"
brew "wget"
brew "xsv"
brew "youtubedr"
brew "yq"
brew "zinit"
brew "zoxide"
