# cask "claude-code" # The brew version of claude code does not get updates quickly, use their official install path
cask "1password-cli"
cask "codex"
cask "docker-desktop"
cask "font-fira-code-nerd-font"

# brew "air" This is NOT the golang filewatcher, but something related to R
brew "angle-grinder"
brew "ansible"
brew "atuin"
brew "bat"
brew "bottom" # btm, ytop replacement
brew "bun"
brew "colima"
brew "coreutils"
brew "direnv"
brew "dive"
brew "dust"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gemini-cli"
brew "gh"
brew "git"
brew "git-extras"
brew "git-lfs"
brew "glab"
brew "glib"
brew "glow"
brew "gnupg"
brew "golang-migrate"
brew "graphviz"
brew "hcloud"
brew "hyperfine"
brew "jq"
brew "k9s"
brew "krew"
brew "kustomize"
brew "lazygit"
brew "lsd"
brew "luarocks"
brew "make"
brew "merman-cli"
brew "mise" # asdf replacement
brew "mole"
brew "neovim"
brew "playwright-cli"
brew "pandoc"
brew "poppler" # pdftotext
brew "procs"
brew "rdap"
brew "rename"
brew "ripgrep"
brew "sd"
brew "shellcheck"
brew "sqlite3"
brew "starship"
brew "teleport"
brew "tokei"
brew "tree"
brew "uv"
brew "wget"
brew "xan"
brew "youtubedr"
brew "yq"
brew "zinit"
brew "zoxide"
